on:
    workflow_dispatch:
jobs:
    actions-job:
        runs-on: ubuntu-latest
        steps:
            - name: say hello
              uses: .github/actions/greetingt@v1
              with:
                  name: yacin
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 