name: First workflow

on:
  push: 
    branches: 
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print a welcome message
        run: echo "welcome"

      - name: checkout repo
        uses: actions/checkout@v6.0.3

      - name: list repo file
        run: ls -la
