on:
  workflow_dispatch: 
    inputs:
      environment:
        description: "choose envo"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - prod   
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy app
        run: echo " deploying this app  ${{ inputs.environment }} "
